# This is the workflow file that calls a reusable workflow

# The name of the workflow as it appears in the GitHub Actions UI
name: Call Reusable Workflow

# Trigger type: this workflow runs manually from the GitHub UI
on:
  workflow_dispatch

jobs:
  # Define a job that uses a reusable workflow
  call-test-workflow:
    # This tells GitHub to use a reusable workflow from a specific path and branch
    uses: iroshanaRavishan/github-actions-demo/.github/workflows/reusable-test.yml@main

    # Pass required input variables to the reusable workflow
    with:
      environment: dev+local    # Providing a string input named 'environment'

    # Pass required secrets to the reusable workflow
    secrets:
      MY_API_KEY: ${{ secrets.MY_API_KEY }}  # Forwarding the secret from the current repo
