name: CI for NodeJS App

# Trigger the workflow on push or pull request to main or dev branches
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Use the latest Ubuntu environment for running the job

    steps:
      # Step 1: Checkout the repository to the GitHub runner
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js environment with version 18
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Step 3: Install project dependencies using a clean install
      - name: Install dependencies
        run: npm ci

      # Step 4: Run ESLint to perform code quality checks
      - name: Lint code with ESLint
        run: npm run lint

      # Step 5: Run Jest tests
      - name: Run tests
        run: npm test

      - name: Run API Tests with Newman
        run: |
          # Start the Node.js server in the background using nohup to keep it running after this step ends
          nohup node src/server/start.js &

          # Wait a few seconds to ensure the server has fully started before running the tests
          sleep 3

          # Execute the Newman API tests
          npm run api-test

