# Name of the workflow displayed in the GitHub Actions UI
name: Testing Workflow Variables

# Trigger type: this workflow runs manually from the GitHub UI
on:
  workflow_dispatch

# Global environment variables accessible to all jobs
env: 
  # This variable can be accessed within any job or step
  cloud: Google-Cloud-platform

jobs:
  # Start of a job named 'welcome_job'
  welcome_job: 
    # This job runs on a GitHub-hosted Ubuntu Linux runner
    runs-on: ubuntu-latest

    # Environment variables scoped to this job only
    env:
      Greeting: Hello

    steps: 
      # A step named "Welcome"
      - name: "Welcome"
        # This command prints a greeting message using:
        # - job-level env variable: $Greeting
        # - step-level env variable: $name
        # - workflow-level env variable: $cloud
        # - GitHub variable from repository or organization: ${{ vars.PROJECT_ID }}
        run: echo "$Greeting $name. You work in $cloud. Your project is ${{ vars.PROJECT_ID }}"
        # Step-level environment variable (only for this step)
        env:
          name: Iroshana
