# Name of the workflow displayed in the GitHub Actions UI
name: Testing Secret Variables

# Trigger type: this workflow runs manually via the "Run workflow" button
on:
    workflow_dispatch

# Global environment variable to enable step-level debug logging (shows more logs in the Actions UI)
env:
    ACTIONS_STEP_DEBUG: true

jobs:
    # A job named 'test_context_variables'
    test_context_variables:
        # This job will run on the latest Ubuntu GitHub-hosted runner
        runs-on: ubuntu-latest

        steps:
            # A step named "Checking secret Variables"
            - name: "Checking secret Variables"
              # This script echoes the value of a GitHub secret (will be masked in logs)
              run: |
                echo "Secret value is : ${{ secrets.MY_API_KEY }}"
